/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsOthersideRouteImport } from './routes/apps.otherside'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsOthersideRoute = AppsOthersideRouteImport.update({
  id: '/apps/otherside',
  path: '/apps/otherside',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/otherside': typeof AppsOthersideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/otherside': typeof AppsOthersideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/otherside': typeof AppsOthersideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps/otherside'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps/otherside'
  id: '__root__' | '/' | '/apps/otherside'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsOthersideRoute: typeof AppsOthersideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/otherside': {
      id: '/apps/otherside'
      path: '/apps/otherside'
      fullPath: '/apps/otherside'
      preLoaderRoute: typeof AppsOthersideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsOthersideRoute: AppsOthersideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
